Update ci-pipeline.yml

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -39,13 +39,13 @@ jobs:
     - name: Lint with flake8
       run: |
         pip install flake8
-        flake8 backend/src || true  # Lint Python code, ignore failures to continue the pipeline
+        flake8 backend || true  # Lint Python code in the 'backend' directory, ignore failures to continue the pipeline
 
     # Step 6: Run Unit Tests (Python)
     - name: Run Python Unit Tests
       run: |
         pip install pytest  # Install pytest
-        pytest backend/src  # Run unit tests for the backend code in src
+        pytest backend  # Run unit tests for the backend code in the backend directory
 
     # Step 7: Run React Unit Tests (Frontend)
     - name: Run React Unit Tests
